export const lgaList: string[] = [
  "Ajingi", "Albasu", "Bagwai", "Bebeji", "Bichi", "Bunkure", "Dala", "Dambatta",
  "Dawakin Kudu", "Dawakin Tofa", "Doguwa", "Fagge", "Gabasawa", "Garko", "Garun Malam",
  "Gaya", "Gezawa", "Gwale", "Gwarzo", "Kabo", "Kano Municipal", "Karaye", "Kibiya", "Kiru",
  "Kumbotso", "Kunchi", "Kura", "Madobi", "Makoda", "Minjibir", "Nassarawa", "Rano", "Rimin Gado",
  "Rogo", "Shanono", "Sumaila", "Takai", "Tarauni", "Tofa", "Tsanyawa", "Tudun Wada",
  "Ungogo", "Warawa", "Wudil"
];

export const lgaWardsMap: any = { // create interface for type safety
  "Ajingi": [
    "Ajingi",
    "Balare",
    "Chula",
    "Dabin-Kanawa",
    "Dundun",
    "Gafasa",
    "Gurduba",
    "Kunkurawa",
    "Toranke",
    "Unguwar Bai"
  ],
  "Albasu": [
    "Albasu Central",
    "Bataiya",
    "Daho",
    "Duja",
    "Fanda",
    "Faragai",
    "Gagarame",
    "Hungu",
    "Saya-Saya",
    "Tsangaya"
  ],
  "Bagwai": [
    "Bagwai",
    "Dangada",
    "Gadanya",
    "Gogori",
    "Kiyawa",
    "Kwajale",
    "Rimin Dako",
    "Romo",
    "Sare-Sare",
    "Wuro Bagga"
  ],
  "Bebeji": [
    "Anadariya",
    "Baguda",
    "Bebeji",
    "Damau",
    "Durmawa",
    "Gargai",
    "Gwarmai",
    "Kofa",
    "Kuki",
    "Rahama",
    "Ranka",
    "Rantan",
    "Tariwa",
    "Wak"
  ],
  "Bichi": [
    "Badume",
    "Bichi",
    "Danzabuwa",
    "Fagolo",
    "Kau-Kau",
    "Kwamarawa",
    "Kyalli",
    "Muntsira",
    "Saye",
    "Waire",
    "Yallami"
  ],
  "Bunkure": [
    "Barkum",
    "Bono",
    "Bunkure",
    "Chirin",
    "Gafan",
    "Gurjiya",
    "Gwamma",
    "Kulluwa",
    "Kumurya",
    "Sanda"
  ],
  "Dala": [
    "Adakawa",
    "Bakin Ruwa",
    "Dala",
    "Dogon Nama",
    "Gobirawa",
    "Gwammaja",
    "Kabuwaya",
    "Kantudu",
    "Kofar Mazugal",
    "Kofar Ruwa",
    "Madigawa",
    "Yalwa"
  ],
  "Dambatta": [
    "Ajumawa",
    "Dambatta West",
    "Fagwalawa",
    "Goron Maje",
    "Gwanda",
    "Gwarabjawa",
    "Kore",
    "Saidawa",
    "San San",
    "Dambatta East"
  ],
  "Dawakin Kudu": [
    "Dabar Kwari",
    "Danbagina",
    "Dawakiji",
    "Dosan",
    "Gano",
    "Gurjiya",
    "Jido",
    "Tanburawa",
    "Tsakuwa",
    "Unguwar Duniya",
    "Yan Barau",
    "Yankatsari",
    "Yargaya",
    "Dawaki",
    "Zogarawa"
  ],
  "Dawakin Tofa": [
    "Danguguwa",
    "Dawaki East",
    "Dawaki West",
    "Dawanau",
    "Ganduje",
    "Gargari",
    "Jalli",
    "Kwa",
    "Marke",
    "Tattarawa",
    "Tumfafi"
  ],
  "Doguwa": [
    "Dadin Kowa",
    "Dogon Kawo",
    "Doguwa",
    "Falgore",
    "Maraku",
    "Riruwai",
    "Shere",
    "Tagwaye",
    "Unguwar Tsohuwa",
    "Zainabi"
  ],
  "Fagge": [
    "Fagge A",
    "Fagge B",
    "Fagge C",
    "Fagge D1",
    "Fagge D2",
    "Kwachiri",
    "Rijiyar Lemo",
    "Sabon Gari East",
    "Sabon Gari West",
    "Yammata"
  ],
  "Gabasawa": [
    "Gabasawa",
    "Garun Danga",
    "Joda",
    "Karmami",
    "Mekiya",
    "Tarauni",
    "Yautar Arewa",
    "Yautar Kudu",
    "Yumbu",
    "Zakirai",
    "Zugachi"
  ],
  "Garko": [
    "Dal",
    "Garin Ali",
    "Garko",
    "Gurjiya",
    "Kafin Malamai",
    "Katumari",
    "Kwas",
    "Raba",
    "Sarina",
    "Zakarawa"
  ],
  "Garun Malam": [
    "Chiromawa",
    "Dakasoye",
    "Dorawar Sallau",
    "Fankurun",
    "Garun Babba",
    "Garun Malam",
    "Jobawa",
    "Kadawa",
    "Makwaro",
    "Yada Kwari"
  ],
  "Gaya": [
    "Balan",
    "Gamarya",
    "Gaya North",
    "Gamoji",
    "Gaya South",
    "Kademi",
    "Kazurawa",
    "Maimakawa",
    "Shagogo",
    "Wudilawa"
  ],
  "Gezawa": [
    "Babawa",
    "Gawo",
    "Gezawa",
    "Jogana",
    "Ketawa",
    "Mesar Tudu",
    "Tsamiya Babba",
    "Tumbau",
    "Wangara",
    "Gezawa_Zango",
    "Sararin Gezawa"
  ],
  "Gwale": [
    "Dandago",
    "Diso",
    "Dorayi",
    "Galadanchi",
    "Gwale",
    "Gyaranya",
    "Goron Dutse",
    "Kabuga",
    "Mandawari",
    "Sani Mai Nagge"
  ],
  "Gwarzo": [
    "Getso",
    "Gwarzo",
    "Jama'a",
    "Kara",
    "Kutama",
    "Lakwaya",
    "Madadi",
    "Mainika",
    "Sabon Birni",
    "Unguwar Tudu"
  ],
  "Kabo": [
    "Dugabau",
    "Durun",
    "Gammo",
    "Garo",
    "Godiya",
    "Gude",
    "Hawaden Galadima",
    "Kabo",
    "Kanwa",
    "Masanawa"
  ],
  "Kano Municipal": [
    "Chedi",
    "Dan Agundi",
    "Gandu Albasa",
    "Kan Karofi",
    "Shahuchi",
    "Kano_Zango",
    "Sharada",
    "She She",
    "Tudun Nufawa",
    "Tudun Wazurchi",
    "Yakasai",
    "Jakara",
    "Zaitawa"
  ],
  "Karaye": [
    "Daura",
    "Kafin Dabga",
    "Kurugu",
    "Kwanyawa",
    "Magajin Gari",
    "Magajin Hajji",
    "Tudun Kaya",
    "Turawa",
    "Yammedi",
    "Yola"
  ],
  "Kibiya": [
    "Durba",
    "Fammar",
    "Fassi",
    "Kadigawa",
    "Kahu",
    "Kibiya 1",
    "Kibiya 2",
    "Nariya",
    "Tarai",
    "Unguwar Gai"
  ],
  "Kiru": [
    "Baawa",
    "Badafi",
    "Bargoni",
    "Bauda",
    "Dangora",
    "Dansoshiya",
    "Dashi",
    "Galadimawa",
    "Kiru",
    "Kogo",
    "Maraku",
    "Tsaudawa",
    "Yako",
    "Yalwa",
    "Zuwo"
  ],
  "Kumbotso": [
    "Chalawa",
    "Chiranchi",
    "Dan Maliki",
    "Danbare",
    "Garun Gawa",
    "Kumbotso",
    "Kureken Sani",
    "Mariri",
    "Naibawa",
    "Panshekara",
    "Unguwar Rimi"
  ],
  "Kunchi": [
    "Bumai",
    "Garun Sheme",
    "Gwarmai",
    "Kasuwar Kuka",
    "Kunchi",
    "Matan Fada",
    "Ridawa",
    "Shamakawa",
    "Shuwaki",
    "Yandadi"
  ],
  "Kura": [
    "Dalili",
    "Dan Hassan",
    "Dukawa",
    "Gundutse",
    "Karfi",
    "Kosawa",
    "Sarkin Kura",
    "Kurun Sumau",
    "Rigar Duka",
    "Tanawa"
  ],
  "Madobi": [
    "Burji",
    "Cinkoso",
    "Galinja",
    "Gora",
    "Kafin Agur",
    "Kanwa",
    "Kauran Mata",
    "Kubaraci",
    "Kwankwaso",
    "Madobi",
    "Rikadawa",
    "Yakun"
  ],
  "Makoda": [
    "Babbar Ruga",
    "Durma",
    "Jibga",
    "Kadan Dani",
    "Koguna",
    "Tabo",
    "Maitsidau",
    "Makoda",
    "Satame",
    "Tangaji",
    "Wailare"
  ],
  "Minjibir": [
    "Azore",
    "Gandurwawa",
    "Kantama",
    "Kunya",
    "Kuru",
    "Kwarkiya",
    "Minjibir",
    "Sarbi",
    "Tsakiya",
    "Tsakuwa",
    "Wasai"
  ],
  "Nassarawa": [
    "Dakata",
    "Gama",
    "Gawuna",
    "Giginyu",
    "Gwagwarwa",
    "Hotoro North",
    "Hotoro South",
    "Kaura Goje",
    "Kawaji",
    "Tudun Murtala",
    "Tudun Wada"
  ],
  "Rano": [
    "Rano Dawaki",
    "Lausu",
    "Madachi",
    "Rurum Sabon Gari",
    "Rurum Tsohon Gari",
    "Rano",
    "Saji",
    "Yalwa",
    "Zinyau",
    "Zurgu"
  ],
  "Rimin Gado": [
    "Butu-Butu",
    "Dawakin Gulu",
    "Doka Dawa",
    "Dugurawa",
    "Gulu",
    "Jili",
    "Karofin Yashi",
    "Rimin Gado",
    "Sakara Tsa",
    "Tamawa",
    "Yalwan Danziyal",
    "RiminGado_Zango"
  ],
  "Rogo": [
    "Beli",
    "Falgore",
    "Fulatan",
    "Gwangwan",
    "Jajaye",
    "Rogo Ruma",
    "Rogo Sabon Gari",
    "Ruwan Bago",
    "Zarewa",
    "Zoza"
  ],
  "Shanono": [
    "Alajawa",
    "Dutsen Bakoshi",
    "Faruruwa",
    "Goron Dutse",
    "Kadamu",
    "Kokiya",
    "Leni",
    "Shakogi",
    "Shanono",
    "Tsaure"
  ],
  "Sumaila": [
    "Gala",
    "Gani",
    "Garfa",
    "Gediya",
    "Kanawa",
    "Magami",
    "Masu",
    "Rimi",
    "Rumo",
    "Sitti",
    "Sumaila"
  ],
  "Takai": [
    "Bagwaro",
    "Durbunde",
    "Fajewa",
    "Falali",
    "Farun Ruwa",
    "Kachako",
    "Karfi",
    "Kuka",
    "Takai",
    "Zuga"
  ],
  "Tarauni": [
    "Babban Giji",
    "Darmanawa",
    "Daurawa",
    "Gyadi Gyadi Arewa",
    "Gyadi Gyadi Kudu",
    "Hotoro",
    "Tarauni",
    "Unguwa Uku Cikin Gari",
    "Unguwa Uku Kauyen Alu",
    "Unguwar Gano"
  ],
  "Tofa": [
    "Dindere",
    "Doka",
    "Gajida",
    "Ginsawa",
    "Janguza",
    "Jauben Kudu",
    "Kwami",
    "Lambu",
    "Langel",
    "Tofa",
    "Unguwar Rimi",
    "Wangara",
    "Yalwa Karama",
    "Yanoko",
    "Yarimawa"
  ],
  "Tsanyawa": [
    "Daddarawa",
    "Dunbulum",
    "Gozarki",
    "Gurun",
    "Kabagiwa",
    "Tatsan",
    "Tsanyawa",
    "Yankamaye",
    "Yanganau",
    "Zarogi"
  ],
  "Tudun Wada": [
    "Baburi",
    "Burun-Burun",
    "Dalawa",
    "Jandutse",
    "Jita",
    "Karefa",
    "Nata-Ala",
    "Sabon Gari",
    "Shuwaki",
    "Tsohon Gari",
    "Yaryasa"
  ],
  "Ungogo": [
    "Bachirawa",
    "Fanisau",
    "Gayawa",
    "Kadawa",
    "Karo",
    "Rangaza",
    "Rijiyar Zaki",
    "Tudun Fulani",
    "Ungogo",
    "Yada Kunya",
    "Ungogo_Zango"
  ],
  "Warawa": [
    "Amarawa",
    "Danlasan",
    "Garin Dau",
    "Gogel",
    "Imawa",
    "Jemagu",
    "Jigawa",
    "Juma Galadima",
    "Katarkawa",
    "Madari",
    "Tamburawan Gabas",
    "Tanagar",
    "Warawa",
    "Yan Dala",
    "Yangizo"
  ],
  "Wudil": [
    "Achika",
    "Dagumawa",
    "Dankaza",
    "Darki",
    "Indabo",
    "Kausani",
    "Lajawa",
    "Utai",
    "Wudil",
    "Sabon Gari"
  ]
}